### ISSUE TITLE
Broken composer dependency

### ISSUE THREAD

**Issue by AntoninSajboch** [mustached/cutycapt-php#2]
composer require marktopper/cutycapt-php

Using version ^1.0 for marktopper/cutycapt-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - marktopper/cutycapt-php 1.0.1 requires marktopper/validator-php 1.* -> no matching package found.
    - marktopper/cutycapt-php 1.0 requires marktopper/validator-php 1.* -> no matching package found.
    - Installation request for marktopper/cutycapt-php ^1.0 -> satisfiable by marktopper/cutycapt-php[1.0, 1.0.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by marktopper** [comment]
Use `composer require mustached/cutycapt-php dev-master`.
